#!/usr/bin/env python3

# Author: Jeffrey Grover
# Purpose: Convert a shortstack full report file to bed6 format
# Created: 11/2017

# This script accepts a

import csv
from argparse import ArgumentParser


def ssfullreport_to_bed(input_full_report, output_bed):
    with open(input_full_report, 'r') as input_handle:
        with open(output_bed, 'w') as output_handle:
            input_reader = csv.reader(input_handle)
            output_writer = csv.writer(output_handle, delimiter='\t')
            next(input_reader)
            for row in input_reader:
                chromosome = row[0].split(':')[0]
                start = int(row[0].split(':')[1].split('-')[0]) - 1  # 0-based
                stop = int(row[0].split(':')[1].split('-')[1])  # 1-based
                name = row[1]
                score = '.'
                strand = row[7]
                output_writer.writerow(
                    [chromosome, start, stop, name, score, strand])


# Parse command line options

parser = ArgumentParser(
    description='Convert a shortstack full report file generated by '
    'shortstack_results_counts_combine.sh')
parser.add_argument(
    'ssfullreport',
    help='A shortstack full report file to convert',
    metavar='.csv')

input_full_report = parser.parse_args().ssfullreport
output_bed = input_full_report.rsplit('.', 1)[0] + '.bed'

# Convert the file

ssfullreport_to_bed(input_full_report, output_bed)
